version: '3.8'

services:
  todo:
    build: .
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:14.0
    env_file: .env
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
